---

# This file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. Due to how `ports` directive is merged with two files.
#
# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker compose up

version: "3.8"
services:

  web:
    ports:
      # We only bind ports directly in development:
      - "8000:8000"
    volumes:
      # We only mount source code in development:
      - .:/code
    build:
      # Needed for fixing permissions of files created by Docker
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}

  fakeapi:
    image: "vimagick/json-server:latest"
    entrypoint: ''
    command: node server.js
    ports:
      - "4242:4242"
    volumes:
      - ./docker/fakeapi:/data
    networks:
      - webnet
    environment:
      NODE_PATH: '/usr/lib/node_modules'
    env_file: ./config/.env

networks:
  # Fake API network:
  webnet:
